In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[2.2266e+27, 7.4129e-43, 2.2266e+27],
        [7.4129e-43, 2.2266e+27, 7.4129e-43],
        [2.2266e+27, 7.4129e-43, 2.2266e+27],
        [7.4129e-43, 2.2266e+27, 7.4129e-43],
        [2.2266e+27, 7.4129e-43, 2.2266e+27]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.5971, 0.7997, 0.4785],
        [0.8723, 0.6712, 0.4466],
        [0.3803, 0.2350, 0.5564],
        [0.9091, 0.5996, 0.0304],
        [0.2297, 0.4473, 0.0513]])


In [11]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
torch.tensor([1.23,3])

tensor([1.2300, 3.0000])

In [6]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
#正規分布
x = torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[ 1.3058, -1.2711, -0.1341],
        [-1.7062,  0.4860, -1.8426],
        [ 1.3860,  1.2068,  0.8641],
        [-0.3627, -0.8515, -0.2970],
        [-0.1875, -0.3065, -1.0364]])


In [8]:
#0から18まで2こ飛ばしで生成
x = torch.arange(0,19,2)
print(x)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


In [9]:
#4つの要素を0から3までで生成
x = torch.linspace(0,3,4)
print(x)

tensor([0., 1., 2., 3.])


In [10]:
x = torch.FloatTensor([5,6,7])
print(x)
print(x.dtype)

tensor([5., 6., 7.])
torch.float32


In [13]:
x = torch.tensor([5,6,7],dtype=torch.int)
print(x)

tensor([5, 6, 7], dtype=torch.int32)


In [14]:
#シード
torch.manual_seed(42)
x = torch.rand(2,3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [16]:
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [17]:
x.dtype

torch.float32

In [22]:
x.size()

torch.Size([2, 3])

In [24]:
x.shape

torch.Size([2, 3])

In [25]:
x = torch.rand(5,3)
print(x)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696]])


In [26]:
y = torch.rand(5,3)
print(y)

tensor([[0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])


In [27]:
#要素同士の和
print(x + y)

tensor([[0.6979, 1.0906, 1.7725],
        [0.2385, 1.2041, 0.9524],
        [1.0688, 1.1149, 0.7473],
        [1.3810, 0.9607, 1.4599],
        [0.8498, 0.9651, 1.0786]])


In [28]:
result = torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[0.6979, 1.0906, 1.7725],
        [0.2385, 1.2041, 0.9524],
        [1.0688, 1.1149, 0.7473],
        [1.3810, 0.9607, 1.4599],
        [0.8498, 0.9651, 1.0786]])


In [41]:
y.add_(x)
print(y)

tensor([[ 3.7768, 10.6143, 13.0617],
        [ 1.8367, 12.4193,  8.0753],
        [11.5016,  7.9275,  9.6404],
        [ 6.5338, 11.5860,  8.3468],
        [ 4.0488,  8.4945,  4.3142]])


In [42]:
print(y[:,1])

tensor([10.6143, 12.4193,  7.9275, 11.5860,  8.4945])


In [43]:
print(y[0,:])

tensor([ 3.7768, 10.6143, 13.0617])


In [44]:
print(y[2:,1:])

tensor([[ 7.9275,  9.6404],
        [11.5860,  8.3468],
        [ 8.4945,  4.3142]])


In [45]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [48]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.0499])
-0.049903348088264465


In [49]:
a = torch.ones(3)
print(a)

tensor([1., 1., 1.])


In [50]:
b = a.numpy()
print(b)

[1. 1. 1.]


In [52]:
#注意：aとbはメモリを共有している
a.add_(3)
print(a)
print(b)

tensor([7., 7., 7.])
[7. 7. 7.]


In [53]:
a = np.ones(3)
print(a)

[1. 1. 1.]


In [54]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1.], dtype=torch.float64)


In [56]:
a = torch.arange(1,4,1,dtype=torch.float)
print(a)

tensor([1., 2., 3.])


In [57]:
a.mean()

tensor(2.)

In [58]:
a.sum()

tensor(6.)

In [60]:
print(a.max())
print(a.min())

tensor(3.)
tensor(1.)


In [62]:
a = torch.tensor([1,2,3],dtype=torch.float)
b = torch.tensor([4,5,6],dtype=torch.float)

print(torch.add(a,b).sum())

tensor(21.)


In [63]:
import math
a = torch.tensor([math.radians(30),math.radians(60),math.radians(90)])

In [64]:
print(torch.sin(a))
print(torch.cos(a))
print(torch.tan(a))
print(torch.asin(a))
print(torch.tanh(a))

tensor([0.5000, 0.8660, 1.0000])
tensor([ 8.6603e-01,  5.0000e-01, -4.3711e-08])
tensor([ 5.7735e-01,  1.7321e+00, -2.2877e+07])
tensor([0.5511,    nan,    nan])
tensor([0.4805, 0.7807, 0.9172])


In [67]:
a = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float)
b = torch.tensor([[1,2],[3,4],[5,6]],dtype=torch.float)

In [69]:
print(torch.mm(a,b))

tensor([[22., 28.],
        [49., 64.]])


In [70]:
print(a@b)

tensor([[22., 28.],
        [49., 64.]])
